name: CI
on:
  push:
    branches: [ "master" ]

jobs:
  push-aur-bin:
    runs-on: ubuntu-latest
    container: archlinux:latest
    #needs: [ create-release ]
    steps:
      - name: set up environment
        env:
          SSH_PRIVKEY: ${{ secrets.SSH_PRIVKEY }}
        run: |
          pacman -Sy --noconfirm fakeroot fish git curl openssh
          mkdir -p ~/.ssh
          echo $SSH_PRIVKEY | ssh-add -
          chmod 0600 ~/.ssh/id_rsa
          git config --global user.name Horange321
          git config --global user.email horange321@163.com
          useradd horange
      - name: clone aur
        run: |
          ssh-keyscan aur.archlinux.org >~/.ssh/known_hosts
          GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no' git clone ssh://aur@aur.archlinux.org/pixiv-multiplatform-bin.git aur
          chmod 777 aur
      - name: build
        run: |
          cd /aur
          fish build.fish ${{ github.ref_name }}
          su horange -c 'makepkg --printsrcinfo' >.SRCINFO
      - name: push
        run: |
          git add PKGBUILD .SRCINFO
          git commit -m "${{ github.ref_name }}
          git push
